name: Build and Release Typst

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Disable Preview for Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sed -i 's/#let preview = true/#let preview = false/g' variable.typ
          grep "#let preview" variable.typ

      - name: Build Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: index.typ

      - name: Create Pre-release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: index.pdf
          prerelease: true
          draft: false
          generate_release_notes: true
          fail_on_unmatched_files: true
